[package]
name = "libc"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2018"
build = "build.rs"

[dependencies]
libboard_zynq = { git = "https://git.m-labs.hk/M-Labs/zc706.git" }

[build-dependencies]
cc = { version = "1.0.1" }
