[package]
authors = ["M-Labs"]
name = "core_io"
version = "0.1.20200410"

[lib]
name = "core_io"

[dependencies]
memchr = { version = "2", default-features = false, optional = true }

[features]
alloc = []
collections = ["alloc", "memchr"]
