[workspace]
members = [
  "libdyld",
  "libcoreio",
  "runtime",
  "szl"
]

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
debug = true
# Link-Time Optimization:
# turn off if you get unusable debug symbols.
lto = true
opt-level = 'z'  # Optimize for size.

[patch.crates-io]
core_io = { path = "./libcoreio" }
