[workspace]
members = [
  "libc",
  "libdyld",
  "libdwarf",
  "libio",
  "libunwind",
  "libksupport",
  "runtime",
  "satman"
]

[profile.release]
panic = "abort"
debug = true
codegen-units = 1
opt-level = 2
lto = true
