[workspace]
members = [
  "libc",
  "libdyld",
  "libcoreio",
  "libdwarf",
  "libunwind",
  "runtime",
  "szl"
]

[profile.release]
panic = "abort"
debug = true
codegen-units = 1
opt-level = 'z'
lto = true

[patch.crates-io]
core_io = { path = "./libcoreio" }
